config/routes.rb
Rails.application.routes.draw do
  resources :topics, only: [:index, :show]


  #resources :comments
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  root to: 'pages#home'


  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'tec_news', to: 'pages#tec_news'

  resources :portfolios, except: [:show] do
      put :sort, on: :collection
  end
  # the as: generates a url helper in this cas portolio_show_path
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'
  get 'angular-items', to: 'portfolios#angular'

  resources :blogs do
    member do
      get :toggle_status
    end
  end


  mount ActionCable.server => '/cable'


end

app/models/portfolio.rb
class Portfolio < ApplicationRecord

  has_many :technologies
  # this helper, allows us to create technology objects fromt he paretnt object, in this case is portfolio
  accepts_nested_attributes_for :technologies,
                                            # verifies that attribute name was filled
                                            allow_destroy: true,
                                            reject_if: lambda { |attrs| attrs['name'].blank?}
                                            # reject_if: lambda { |attrs| attrs['name'].blank? }




  validates_presence_of :title, :body

  mount_uploader :thumb_image, PortfolioUploader
  mount_uploader :main_image, PortfolioUploader

  def self.by_position
    order("position ASC")
  end


  #basic custome scope
  # 2 ways
  # 1.
  def self.angular
    where(subtitle: 'Angular')
  end

  # 2.
  scope :ruby_on_rails, -> { where(subtitle: "Ruby on Rails") }



  #call back
  # after the portolio item is instantiated in the new action


  # the ||= operator allows us to only give the values if its nil, so when an update happens it will






end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  layout 'portfolio'
  before_action :set_porfolio, only: [:edit, :show, :update, :destroy]
  access all: [:show, :index, :angular], user: {except: [:destroy, :new, :create, :update, :edit]}, site_admin: :all


  def index
     @portfolio_items = Portfolio.by_position
  end

  def sort
    params[:order].each do |key, value|
      Portfolio.find(value[:id]).update(position: value[:position])
    end
    render nothing: true
  end

  def angular
    @angular_portfolio_items = Portfolio.angular
  end

  def new
    @portfolio = Portfolio.new
  end

  def create
    @portfolio = Portfolio.create(portfolio_params)
      if @portfolio.save
        redirect_to portfolios_path , notice: 'Your portfolio item is now live!'
      else
        render 'new'
      end
  end

  def show

  end

  def edit
    render 'edit'
  end

  def update

    if @portfolio.update(portfolio_params)
      redirect_to portfolio_show_path, notice: 'Your Portfolio item was updated'
      else
        render 'edit'
    end
  end


  def destroy

      if @portfolio.destroy
         redirect_to portfolios_path, notice: 'Portfolio item deleted'
      end
  end




private

  def set_porfolio
     @portfolio = Portfolio.find(params[:id])
  end


  def portfolio_params
    params.require(:portfolio).permit(:title,
                                      :subtitle,
                                      :body,
                                      :main_image,
                                      :thumb_image,
                                      technologies_attributes: [:id, :name, :_destroy]
                                      )
  end



end

app/helpers/portfolios_helper.rb
module PortfoliosHelper

   def image_generator(height:, width:)
    "http://placehold.it/#{height}x#{width}"
  end

  def portfolio_img img, type
    if img.model.main_image? || img.model.thumb_image?
      img
    elsif type == 'thumb'
      image_generator(height: '350', width: '200')
    elsif type == 'main'
      image_generator(height: '600', width: '400')
    end
  end


end

app/views/portfolios/_form.html.erb
<%= form_for(@portfolio) do |f| %>
  <% if @portfolio.errors.any? %>
    <% @portfolio.errors.full_messages.each do |error| %>
      <%= alert_generator error %>
    <% end %>
  <% end %>
  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :subtitle %>
        <%= f.text_field :subtitle, class: 'form-control' %>
      </div>

       <div class="form-group">
        <label class="btn btn-primary">
         Upload a main image file <%= f.file_field :main_image, style: 'display:none' %>
        </label>

       </div>

       <div class="form-group">
        <label class="btn btn-primary">
         Upload a thumb image file <%= f.file_field :thumb_image, style: 'display:none' %>
        </label>
       </div>


    </div>

    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, class: 'form-control', rows: 13 %>

      </div>
    </div>
  </div>
  <br>

  <div class="col-md-12">
    <h2>Technologies used:</h2>
    <div>
      <<%= f.fields_for :technologies do |technology_form| %>
      <p> <%= render 'technology_fields', f: technology_form %></p>
      <% end %>

      <div>
        <%= link_to_add_association 'Add tech', f, :technologies %>
      </div>
    </div>

    <div class="form-group">
      <%= f.submit "save portfolio", class: 'btn btn-primary btn-block ' %>
    </div>

  </div>



<% end %>

app/views/portfolios/_portfolio_item.html.erb
<div class="col-md-4">
  <div class="card" data-id="<%= portfolio_item.id %>">
    <%= image_tag portfolio_img(portfolio_item.thumb_image, 'thumb'), width: '100%' %>
    <p class="card-text">
      <span>
        <%= link_to portfolio_item.title, portfolio_show_path(portfolio_item) %>
      </span>
      <%= portfolio_item.subtitle %>
    </p>
  </div>


</div>

app/views/portfolios/_technology_fields.html.erb
<div class="class-form nested-fields">
  <%= f.label :name %>
  <%= f.text_field :name, class: 'technology_form' %>
  <%= link_to_remove_association 'Remove Technology', f  %>
</div>

app/views/portfolios/angular.html.erb
<h1>Angular portfolio Items</h1>

<%= link_to 'New Portfolio Item', new_portfolio_path if logged_in?(:site_admin) %>

<% @angular_portfolio_items.each do |f| %>
  <p><%= f.title %></p>
  <h2><%= link_to f.subtitle, portfolio_show_path(f) %></h2>
  <p><%= f.body %></p>
  <p><%= f.main_image %></p>
  <%= image_tag(f.thumb_image) unless f.thumb_image.nil? %>
  <p>
    <%= link_to "Show", portfolio_show_path(f) %> ||  <%=  link_to 'Edit', edit_portfolio_path(f) if logged_in?(:site_admin) %> ||
    <%= link_to 'Destroy', portfolio_path(f), method: :delete, data: { confirm: 'Are you sure?' } if logged_in?(:site_admin) if logged_in?(:site_admin)%>
  </p>

  <br/>
  <br/>
<% end %>

<br/>
<br/>

app/views/portfolios/edit.html.erb
<div class="container portfolio-container">
  <%= render 'form', porfolio_item: @porfolio_item %>
</div>

app/views/portfolios/index.html.erb
<div class="album text-muted">
  <div class="container">
    <div class="row sortable">
      <%= source_helper("alert alert-warning") %>
      <%#= link_to 'New Portfolio Item', new_portfolio_path if logged_in?(:site_admin)%>
      <%= render partial: 'portfolio_item', collection: @portfolio_items %>
    </div>
  </div>
</div>

app/views/portfolios/new.html.erb
<div class="container portfolio-container">
  <h1>Create a new Porfolio Item</h1>

  <%= render 'form', porfolio_item: @porfolio_item %>
</div>

app/views/portfolios/show.html.erb
<div class="container portfolio-container">
  <div class="row">
    <div class="col-md-7">
       <%= image_tag portfolio_img(@portfolio.thumb_image, 'main'), width: '100%' %>
    </div>
    <div class="col-md-5">
      <h1> <%= @portfolio.title %></h1>

      <hr>

      <em> <%= @portfolio.subtitle %>  </em>
      <p> <%= @portfolio.body %> </p>

      <hr>

      <h3>Thechnologies Used</h3>

      <% @portfolio.technologies.each do |t|  %>
          <p><%= t.name %></p>
      <% end %>

      <% if logged_in?(:site_admin) %>
        <div class="col-md-12">
          <%=  link_to "Edit Item", edit_portfolio_path(@portfolio), class: 'btn btn-warning' %>
        </div>
      <% end %>

    </div>
  </div>
</div>